import { ServiceType } from '@handycall/shared';

export const SERVICE_TYPE_OPTIONS: Array<{ value: ServiceType; label: string }> = [
  { value: ServiceType.HANDYMAN, label: 'Handyman' },
  { value: ServiceType.PEST_CONTROL, label: 'Pest Control' },
  { value: ServiceType.ELECTRICIAN, label: 'Electrician' },
  { value: ServiceType.PLUMBING, label: 'Plumbing' },
  { value: ServiceType.HVAC, label: 'HVAC' },
  { value: ServiceType.LANDSCAPING, label: 'Landscaping' },
  { value: ServiceType.LAWN_CARE, label: 'Lawn Care' },
  { value: ServiceType.CLEANING, label: 'Cleaning' },
  { value: ServiceType.CARPET_CLEANING, label: 'Carpet Cleaning' },
  { value: ServiceType.WINDOW_CLEANING, label: 'Window Cleaning' },
  { value: ServiceType.PRESSURE_WASHING, label: 'Pressure Washing' },
  { value: ServiceType.POOL_SERVICE, label: 'Pool Service' },
  { value: ServiceType.TREE_SERVICE, label: 'Tree Service' },
  { value: ServiceType.ROOFING, label: 'Roofing' },
  { value: ServiceType.PAINTING, label: 'Painting' },
  { value: ServiceType.FLOORING, label: 'Flooring' },
  { value: ServiceType.REMODELING, label: 'Remodeling' },
  { value: ServiceType.GARAGE_DOOR, label: 'Garage Door' },
  { value: ServiceType.APPLIANCE_REPAIR, label: 'Appliance Repair' },
  { value: ServiceType.AUTO_MECHANIC, label: 'Auto Mechanic' },
  { value: ServiceType.LOCKSMITH, label: 'Locksmith' },
  { value: ServiceType.MOVING, label: 'Moving' },
  { value: ServiceType.JUNK_REMOVAL, label: 'Junk Removal' },
  { value: ServiceType.IRRIGATION, label: 'Irrigation' },
  { value: ServiceType.SNOW_REMOVAL, label: 'Snow Removal' },
  { value: ServiceType.FENCING, label: 'Fencing' },
  { value: ServiceType.CONCRETE, label: 'Concrete' },
  { value: ServiceType.SOLAR, label: 'Solar' },
  { value: ServiceType.SECURITY, label: 'Security Systems' },
  { value: ServiceType.OTHER, label: 'Other' },
];
